spring.application.name=e-commerce

# Mudança principal: o Spring vai buscar esses valores no servidor
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Swagger
springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs